module.exports = {
  caseType:'operator_approved_production_dispatch', initialState:'job_received',
  states:['job_received','sources_synchronized','constraints_validated','schedule_proposed','operator_approved','dispatched','executing','exception_recovery','outcome_recorded'],
  createRoles:['production_planner','operations_manager'],
  assessmentRoles:['production_planner','operator','safety_reviewer','operations_manager'],
  auditRoles:['operations_manager','safety_reviewer'],
  connectorRoles:['integration_operator','operations_manager'],
  evidenceKinds:['asset_state_snapshot','job_queue_snapshot','constraint_manifest','telemetry_batch_digest','schedule_manifest','operator_approval','dispatch_receipt','execution_feedback','exception_record','maintenance_status','realized_outcome'],
  requiredSignals:['sourceTimestamp','evaluatedAt','staleAfterSeconds','assetStateVersion','jobQueueVersion','constraintVersion','safetyLimitsVerified','offlineBufferComplete','policyVersion'],
  professionalBoundary:'The workflow is advisory and cannot command machinery, PLCs, robots, vehicles, or safety systems; an authorized operator approves dispatch.',
  connectors:[
    {name:'telemetry',purpose:'timestamped batch receipts'},
    {name:'erp',purpose:'job and material snapshots'},
    {name:'wms',purpose:'inventory availability'},
    {name:'tms',purpose:'inbound/outbound status'},
    {name:'scada',purpose:'read-only asset-state references'},
    {name:'gis_weather',purpose:'site and weather snapshots'},
    {name:'cmms',purpose:'maintenance state'},
    {name:'notification',purpose:'operator receipts'},
  ],
  transitions:[
    {from:'job_received',action:'synchronize_sources',to:'sources_synchronized',roles:['integration_operator','production_planner'],requiresEvidence:true},
    {from:'sources_synchronized',action:'validate_constraints',to:'constraints_validated',roles:['production_planner','safety_reviewer'],requiresEvidence:true},
    {from:'constraints_validated',action:'propose_schedule',to:'schedule_proposed',roles:['production_planner'],requiresEvidence:true},
    {from:'schedule_proposed',action:'approve_dispatch',to:'operator_approved',roles:['operator','operations_manager'],requiresEvidence:true,dualControl:true},
    {from:'operator_approved',action:'record_dispatch',to:'dispatched',roles:['operator'],requiresEvidence:true},
    {from:'dispatched',action:'start_execution',to:'executing',roles:['operator'],requiresEvidence:true},
    {from:'executing',action:'open_exception',to:'exception_recovery',roles:['operator','safety_reviewer'],requiresEvidence:true},
    {from:'executing',action:'record_outcome',to:'outcome_recorded',roles:['operator'],requiresEvidence:true,dualControl:true},
    {from:'exception_recovery',action:'record_outcome',to:'outcome_recorded',roles:['operations_manager'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>{const source=Date.parse(x.sourceTimestamp);const evaluated=Date.parse(x.evaluatedAt);const limit=Number(x.staleAfterSeconds);const stale=!Number.isFinite(source)||!Number.isFinite(evaluated)||!Number.isFinite(limit)||limit<=0||evaluated<source||(evaluated-source)/1000>limit;return{disposition:stale||x.safetyLimitsVerified!==true||x.offlineBufferComplete!==true?'fail_safe_manual_fallback':'operator_schedule_review_required',controlCommand:null,stale,versions:{asset:x.assetStateVersion,jobs:x.jobQueueVersion,constraints:x.constraintVersion}};},
};
